In [2]:
import warnings
warnings.filterwarnings("ignore")

import os
import time
import numpy as np
import pandas as pd
import pickle as pkl
import matplotlib.pyplot as plt

import src
from src.reload import deep_reload

np.set_printoptions(suppress=True,precision=5)

In [4]:
#Importing itineraries

itineraries=pkl.load(open('Data/Generated_Data/itineraries.pkl','rb'))

In [196]:
#Test Simulation
deep_reload(src)

# n=np.random.randint(0,len(itineraries)-1)
# n=146781
# n=12453
# n=142611
print(n)

bev=src.bev.Vehicle(
    itineraries[n]['trips'],
    # home_charger_power=0,
    # work_charger_power=0,
    # en_route_charger_power=0,
    # destination_charger_likelihood=1,
    bounds_violation_penalty=1e4,
    initial_soc=.5,
    final_soc=.5,
    final_soc_penalty=1e3,
    quanta_dc_charging=21,
    quanta_ac_charging=21,
    quanta_soc=21,
    cost_multiplier=1,
    time_multiplier=1,
    tiles=7
    )

optimal_strategy,optimal_control,state_trace,cost_trace=bev.Solve()

120493


In [197]:
state_trace,optimal_control,cost_trace[1],cost_trace.sum(axis=1)

(array([0.5    , 0.49251, 0.56472, 0.52685, 0.48791, 0.47969, 0.45823,
        0.44478, 0.40692, 0.36798, 0.35976, 0.3383 , 0.36039, 0.3529 ,
        0.35857, 0.3207 , 0.28176, 0.27354, 0.25208, 0.29608, 0.25822,
        0.21928, 0.21106, 0.1896 , 0.36243, 0.35494, 0.35832, 0.32046,
        0.28152, 0.2733 , 0.25184, 0.28725, 0.24938, 0.21044, 0.20222,
        0.18076, 0.36301, 0.35551, 0.35826, 0.32039, 0.28145, 0.27323,
        0.25177, 0.28725, 0.24938, 0.21045, 0.20222, 0.18076, 0.25652,
        0.24902, 0.25903, 0.22116, 0.18223, 0.174  , 0.15254, 0.17835,
        0.23885, 0.19992, 0.19169, 0.17023, 0.36369, 0.3562 , 0.35817,
        0.32031, 0.28137, 0.27315, 0.25169, 0.28725, 0.24939, 0.21045,
        0.20223, 0.18077, 0.30976, 0.30227, 0.30864, 0.27077, 0.23184,
        0.22361, 0.20216, 0.28521, 0.24735, 0.20841, 0.20019, 0.17873,
        0.52287]),
 [array([   0.     ,    0.     , 1950.     ,    0.     ,    0.     ,
            0.     ,    0.     ,  432.     ,    0.     ,    

In [195]:
optimal_strategy[0][-1],optimal_strategy[1][-1]

(array([0.5 , 0.45, 0.4 , 0.35, 0.3 , 0.25, 0.2 , 0.15, 0.1 , 0.1 , 0.05,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]))

In [765]:
bev.dwells[-1]*.2

9360.0

In [396]:
np.interp(.379,bev.x,optimal_strategy[0][-1])

0.0905

In [345]:
bev.x,bev.u1,bev.u2

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
        0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
        0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
        0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
        0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [458]:
bev.destination_charger_availability

array([0.  , 0.1 , 0.05, 0.05, 0.05, 0.05, 0.1 , 0.05, 0.05, 0.05, 0.05,
       0.1 , 0.  , 0.1 , 0.05, 0.05, 0.05, 0.05, 0.1 , 0.05, 0.05, 0.05,
       0.05, 0.1 , 0.  , 0.1 , 0.05, 0.05, 0.05, 0.05, 0.1 , 0.05, 0.05,
       0.05, 0.05, 0.1 , 0.  , 0.1 , 0.05, 0.05, 0.05, 0.05, 0.1 , 0.05,
       0.05, 0.05, 0.05, 0.1 , 0.  , 0.1 , 0.05, 0.05, 0.05, 0.05, 0.1 ,
       0.05, 0.05, 0.05, 0.05, 0.1 , 0.  , 0.1 , 0.05, 0.05, 0.05, 0.05,
       0.1 , 0.05, 0.05, 0.05, 0.05, 0.1 , 0.  , 0.1 , 0.05, 0.05, 0.05,
       0.05, 0.1 , 0.05, 0.05, 0.05, 0.05, 0.1 ])

In [522]:
#Test Simulation
deep_reload(src)

# n=np.random.randint(0,len(itineraries)-1)
# n=146781
# n=12453
print(n)

bev=src.bev_s.Vehicle(
    itineraries[n]['trips'],
    home_charger_likelihood=.1,
    work_charger_likelihood=0,
    # home_charger_power=0,
    # work_charger_power=0,
    # en_route_charger_power=0,
    # destination_charger_likelihood=0,
    bounds_violation_penalty=1e4,
    initial_soc=.5,
    final_soc=.5,
    final_soc_penalty=1e3,
    quanta_dc_charging=21,
    quanta_ac_charging=21,
    quanta_soc=21,
    cost_multiplier=0,
    time_multiplier=1,
    tiles=7
    )

optimal_strategy,optimal_control,state_trace,cost_trace=bev.Solve()
s=itineraries[n]['trips'].shape[0]
print(cost_trace[:,:5*s].sum(axis=1))

120493
[2465.40427   71.44962]


In [523]:
state_trace,optimal_control

(array([0.5    , 0.49251, 0.48479, 0.44692, 0.40799, 0.49813, 0.47668,
        0.44552, 0.40765, 0.36872, 0.36049, 0.33904, 0.30788, 0.30039,
        0.29267, 0.2548 , 0.21587, 0.30602, 0.28456, 0.43048, 0.39261,
        0.35368, 0.34545, 0.32399, 0.29284, 0.28535, 0.27762, 0.23976,
        0.20082, 0.1926 , 0.17114, 0.13999, 0.10212, 0.65584, 0.64762,
        0.62616, 0.59501, 0.58751, 0.57979, 0.54193, 0.50299, 0.59314,
        0.57168, 0.54053, 0.50266, 0.46373, 0.4555 , 0.43404, 0.40289,
        0.3954 , 0.54753, 0.50967, 0.47073, 0.46251, 0.44105, 0.40989,
        0.37203, 0.33309, 0.32487, 0.30341, 0.27225, 0.26476, 0.25704,
        0.21917, 0.18024, 0.17201, 0.15056, 0.29648, 0.25861, 0.21967,
        0.21145, 0.18999, 0.15884, 0.15134, 0.14362, 0.10576, 0.28046,
        0.27224, 0.25078, 0.21963, 0.18176, 0.14282, 0.1346 , 0.11314,
        0.13998]),
 [array([   0.,    0.,    0.,    0.,    0., 2400.,    0.,    0.,    0.,
            0.,    0.,    0.,    0.,    0.,    0.,    0.,

In [202]:
optimal_strategy[0][-1],optimal_strategy[1][-1]

(array([0.35, 0.3 , 0.4 , 0.35, 0.3 , 0.25, 0.2 , 0.15, 0.1 , 0.1 , 0.05,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]),
 array([0.05, 0.05, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]))

In [163]:
state_trace,optimal_control,cost_trace.sum(axis=1)

(array([0.5    , 0.49836, 0.49672, 0.4928 , 0.47692, 0.4747 , 0.47414,
        0.4588 , 0.44926, 0.44683, 1.74952, 1.74788, 1.94299, 1.93907,
        1.92319, 1.92097, 1.92041, 1.90507, 1.89553, 1.8931 , 2.68753,
        2.68588, 2.88099, 2.87707, 2.86119, 2.85898, 2.85841, 2.84307,
        2.83353, 2.8311 , 3.62553, 3.62389, 3.819  , 3.81507, 3.7992 ,
        3.79698, 3.79642, 3.78108, 3.77154, 3.76911, 4.56354, 4.56189,
        4.757  , 4.75308, 4.7372 , 4.73499, 4.73442, 4.71908, 4.70954,
        4.70711, 5.50154, 5.4999 , 5.695  , 5.69108, 5.67521, 5.67299,
        5.67243, 5.65709, 5.72133, 5.7189 , 6.51333, 6.51168, 6.70679,
        6.70287, 6.68699, 6.68478, 6.68421, 6.66887, 6.73311, 6.73068,
        6.72828]),
 [array([    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
             0.,     0., 19440.,     0.,  4800.,     0.,     0.,     0.,
             0.,     0.,     0.,     0., 19440.,     0.,  4800.,     0.,
             0.,     0.,     0.,     0.,     0.,    

In [272]:
deep_reload(src)
def ChargeCost(itin,hc):
    
    bev=src.bev_s.Vehicle(
        itin,
        home_charger_likelihood=hc,
        # home_charger_power=0,
        work_charger_power=0,
        en_route_charger_power=0,
        destination_charger_likelihood=0,
        final_soc_penalty=1e10,
        quanta_dc_charging=11,
        quanta_ac_charging=11,
        quanta_soc=11,
        )

    optimal_strategy,optimal_control,state_trace,cost_trace=bev.Solve()
    
    return cost_trace.sum(axis=1)
m=20
hc=np.linspace(0,1,m)
tc=np.zeros((10,m))
cc=np.zeros((10,m))

t0=time.time()
for idx in range(10):
    for idx1 in range(m):
        tc[idx,idx1],cc[idx,idx1]=ChargeCost(itineraries[n]['trips'],hc[idx1])
print(time.time()-t0)
print(cc.mean(axis=0))

0.667741060256958
[ 0.      45.41443 45.41443 45.41443 45.41443 45.41443 45.23599 45.23599
 45.19229 42.59823 40.12944 39.6036  30.36184 30.02455 30.02455 29.66927
 29.66927 29.32204 29.33362 29.33246]


In [588]:
print(tc.mean(axis=0))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
