In [1]:
import warnings
warnings.filterwarnings("ignore")

import os
import time
import numpy as np
import pandas as pd
import pickle as pkl
import matplotlib.pyplot as plt

import src
from src.reload import deep_reload

np.set_printoptions(suppress=True,precision=5)

In [2]:
#Importing itineraries

itineraries=pkl.load(open('Data/Generated_Data/itineraries.pkl','rb'))

In [90]:
#Test Simulation
deep_reload(src)

# n=np.random.randint(0,len(itineraries)-1)
print(n)

bev=src.bev_lp.Vehicle(
    itineraries[n]['trips'],
    initial_soc=.6,
    final_soc=.5,
    # destination_charger_likelihood=0,
    # home_charger_power=0,
    # work_charger_power=0,
    tiles=4,
    )

# problem=src.bev_lp.LinearProblem(bev)

21113


In [108]:
#Test Simulation
deep_reload(src)

model=src.bev_lp.MixedIntegerProblem(bev)
model.__dict__

({'_ownSolver': True,
  'solver_name': 'CBC',
  'solver': <mip.cbc.SolverCbc at 0x7ffb43599390>,
  'constrs': <mip.lists.ConstrList at 0x7ffb4314ff10>,
  'vars': <mip.lists.VarList at 0x7ffb4357e110>,
  '_status': <OptimizationStatus.LOADED: 6>,
  '_Model__cuts': -1,
  '_Model__cut_passes': -1,
  '_Model__clique': -1,
  '_Model__preprocess': -1,
  '_Model__cuts_generator': None,
  '_Model__lazy_constrs_generator': None,
  '_Model__start': None,
  '_Model__threads': 0,
  '_Model__lp_method': <LP_Method.AUTO: 0>,
  '_Model__n_cols': 0,
  '_Model__n_rows': 0,
  '_Model__gap': inf,
  '_Model__store_search_progress_log': False,
  '_Model__plog': <mip.log.ProgressLog at 0x7ffb4345d090>,
  '_Model__integer_tol': 1e-06,
  '_Model__infeas_tol': 1e-06,
  '_Model__opt_tol': 1e-06,
  '_Model__max_mip_gap': 0.0001,
  '_Model__max_mip_gap_abs': 1e-10,
  '_Model__seed': 0,
  '_Model__round_int_vars': True,
  '_Model__sol_pool_size': 10,
  '_Model__max_seconds_same_incumbent': inf,
  '_Model__max_node

In [98]:
deep_reload(src)

nlp=src.bev_lp.NonLinearProblem(bev)

[12356571.74371 12350407.32778 12356571.74371 12350407.32778
 12356571.74371 12350407.32778 12356571.74371 12350407.32778] 177120000.0 [12100 12100 12100 12100 12100 12100 12100 12100] [150000. 150000. 150000. 150000. 150000. 150000. 150000. 150000.] 295200000.0 60 960


In [99]:
from pyoptsparse import SLSQP, IPOPT, Optimization, NSGA2

optOptions = {"IPRINT": -1}
optOptions={}
opt = IPOPT(options=optOptions)

# rst begin solve
# Solve
sol = opt(nlp, sens="FD")

0 0 0 0
60 60 0 0
60 60 0 0
60 60 0 0
60 60 0 0
60 60 0 0
60 60 0 0
60 60 0 0
60 60 0 0
960.000001 0 960 1e-06
960.000001 0 960 1e-06
960.000001 0 960 1e-06
960.000001 0 960 1e-06
960.000001 0 960 1e-06
960.000001 0 960 1e-06
960.000001 0 960 1e-06
960.000001 0 960 1e-06
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.07999992 480 7680 0.07999992
8160.08000092 480 7680 0.08000092
8160.08000092 480 7680 0.08000092
8160.08000092 480 7680 0.08000092
8160.08000092 480 7680 0.08000092
8160.08000092 480 7680 0.08000092
8160.08000092 480 7680 0.08000092
8160.08000092 480 7680 0.08000092
8160.08000092 480 7680 0.08000092
8160.376305223656 480 7680 0.37630522365675534
8160.376305223656 480 7680 0.37630522365675534
8160.376305223656 480 7680 0.37630522365675534
8160.3763

In [100]:
sol.xStar,sol.fStar

(OrderedDict([('lrcd',
               array([644.04332, 647.69675, 644.04332, 647.69675, 644.21088, 952.89873,
                      526.63802, 775.61809])),
              ('hrcd',
               array([ 0.00005,  0.00005,  0.00005,  0.00005,  0.00005,  0.00005,
                       0.00005, -0.     ]))]),
 array([7200.00035]))

In [102]:
sol.xStar['hrcd']>0

array([ True,  True,  True,  True,  True,  True,  True, False])

In [17]:
# First party modules
from pyoptsparse import SLSQP, Optimization


# rst begin objfunc
def objfunc(xdict):
    x = xdict["xvars"]
    funcs = {}
    funcs["obj"] = -x[0] * x[1] * x[2]
    conval = [0] * 2
    conval[0] = x[0] + 2.0 * x[1] + 2.0 * x[2] - 72.0
    conval[1] = -x[0] - 2.0 * x[1] - 2.0 * x[2]
    funcs["con"] = conval
    fail = False

    return funcs, fail


# rst begin optProb
# Optimization Object
optProb = Optimization("TP037 Constraint Problem", objfunc)

# rst begin addVar
# Design Variables
optProb.addVarGroup("xvars", 3, "c", lower=[0, 0, 0], upper=[42, 42, 42], value=10)

# rst begin addCon
# Constraints
optProb.addConGroup("con", 2, lower=None, upper=0.0)

# rst begin addObj
# Objective
optProb.addObj("obj")

# rst begin print
# Check optimization problem
print(optProb)

# rst begin OPT
# Optimizer
optOptions = {"IPRINT": -1}
opt = SLSQP(options=optOptions)

# rst begin solve
# Solve
sol = opt(optProb, sens="FD")

# rst begin check
# Check Solution
print(sol)



Optimization Problem -- TP037 Constraint Problem
    Objective Function: objfunc


   Objectives
      Index  Name            Value
          0  obj     0.000000E+00

   Variables (c - continuous, i - integer, d - discrete)
      Index  Name      Type      Lower Bound            Value      Upper Bound     Status
          0  xvars_0      c     0.000000E+00     1.000000E+01     4.200000E+01           
          1  xvars_1      c     0.000000E+00     1.000000E+01     4.200000E+01           
          2  xvars_2      c     0.000000E+00     1.000000E+01     4.200000E+01           

   Constraints (i - inequality, e - equality)
      Index  Name Type          Lower           Value           Upper    Status  Lagrange Multiplier (N/A)
          0  con    i  -1.000000E+20    0.000000E+00    0.000000E+00         u    9.00000E+100
          1  con    i  -1.000000E+20    0.000000E+00    0.000000E+00         u    9.00000E+100
